blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/Coaktion/zendesk-clients-react/discussions
    about: Please ask and answer questions here.